package cloud.timo.TimoCloud.api.events;

public enum EventType {
    PLAYER_CONNECT,
    PLAYER_DISCONNECT,
    PLAYER_SERVER_CHANGE,
    SERVER_REGISTER,
    SERVER_UNREGISTER,
    PROXY_REGISTER,
    PROXY_UNREGISTER,
    CORD_CONNECT,
    CORD_DISCONNECT,

    SG_ONLINE_AMOUNT_CHANGED,

    PG_MAX_AMOUNT_CHANGED,
    PG_MIN_AMOUNT_CHANGED,
    PG_KEEP_FREE_SLOTS_CHANGED,
    PG_MAX_PLAYER_COUNT_CHANGED,
    PG_MAX_PLAYER_COUNT_PER_PROXY_CHANGED,
    PG_BASE_NAME_CHANGED,
    PG_MOTD_CHANGED,
    PG_PRIORITY_CHANGED,
    PG_PROXY_CHOOSE_STRATEGY_CHANGED,
    PG_RAM_CHANGED,
    PG_STATIC_CHANGED,

    B_READY_CHANGED

}