package cloud.timo.TimoCloud.api.events;

public enum EventType {
    PLAYER_CONNECT,
    PLAYER_DISCONNECT,
    PLAYER_SERVER_CHANGE,
    SERVER_REGISTER,
    SERVER_UNREGISTER,
    PROXY_REGISTER,
    PROXY_UNREGISTER,
    CORD_CONNECT,
    CORD_DISCONNECT,

    SG_ONLINE_AMOUNT_CHANGED,

    PG_MAX_AMOUNT_CHANGED,

    B_READY_CHANGED
}
